{
 "title": "ECS：数量",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(ecs_cost_by_neworder_per1month, env)"
   },
   {
    "name": "regionId",
    "label": "regionId",
    "query": "label_values(ecs_cost_by_neworder_per1month, regionId)"
   },
   {
    "name": "status",
    "label": "运行状态",
    "query": "label_values(ecs_cost_by_neworder_per1month, status)"
   },
   {
    "name": "businessLine",
    "label": "业务线",
    "query": "label_values(ecs_cost_by_neworder_per1month, businessLine)"
   },
   {
    "name": "project",
    "label": "项目",
    "query": "label_values(ecs_cost_by_neworder_per1month, project)"
   },
   {
    "name": "serverType",
    "label": "服务类型",
    "query": "label_values(ecs_cost_by_neworder_per1month, serverType)"
   },
   {
    "name": "serverName",
    "label": "服务名称",
    "query": "label_values(ecs_cost_by_neworder_per1month, serverName)"
   },
   {
    "name": "owner",
    "label": "所有者",
    "query": "label_values(ecs_cost_by_neworder_per1month, owner)"
   },
   {
    "name": "applicant",
    "label": "申请人",
    "query": "label_values(ecs_cost_by_neworder_per1month, applicant)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "总机器数量",
   "type": "singlestat",
   "description": "只包含系统盘，未计算数据盘\n计算公式：\n实例类型×实例价格（未折扣，系统盘40G，未包含数据盘）",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ecs_cost_by_neworder_per1month)"
    }
   ]
  },
  {
   "title": "机器数量 by 环境",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ecs_cost_by_neworder_per1month) by (env)",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "机器数量 by regionId",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ecs_cost_by_neworder_per1month) by (regionId)",
     "legendFormat": "{{regionId}}"
    }
   ]
  },
  {
   "title": "机器数量 by 运行状态",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ecs_cost_by_neworder_per1month) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "总成本：新购维度估算",
   "type": "singlestat",
   "description": "只包含系统盘，未计算数据盘\n计算公式：\n实例类型×实例价格（未折扣，系统盘40G，未包含数据盘）",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "currencyJPY",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ecs_cost_by_neworder_per1month)"
    }
   ]
  },
  {
   "title": "机器数量",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count(ecs_cost_by_neworder_per1month{regionId=~\"$regionId\"}) by (regionId)",
     "legendFormat": "{{regionId}}"
    }
   ]
  },
  {
   "title": "机器数量 by 业务线",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ecs_cost_by_neworder_per1month) by (businessLine)",
     "legendFormat": "{{businessLine}}"
    }
   ]
  },
  {
   "title": "机器数量 by 项目",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ecs_cost_by_neworder_per1month) by (businessLine, project)",
     "legendFormat": "{{businessLine}}：{{project}}"
    }
   ]
  },
  {
   "title": "机器数量 by 所有者",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ecs_cost_by_neworder_per1month) by (owner)",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "机器成本：新购维度估算",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(ecs_cost_by_neworder_per1month{regionId=~\"$regionId\"}) by (regionId)",
     "legendFormat": "{{regionId}}"
    }
   ]
  },
  {
   "title": "机器数量 by 服务类型",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ecs_cost_by_neworder_per1month) by (businessLine, project,serverType)",
     "legendFormat": "{{businessLine}}：{{project}}：{{serverType}}"
    }
   ]
  },
  {
   "title": "机器数量 by 服务名称",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ecs_cost_by_neworder_per1month) by (businessLine, project,serverType, serverName)",
     "legendFormat": "{{businessLine}}：{{project}}：{{serverType}}：{{serverName}}"
    }
   ]
  },
  {
   "title": "机器数量 by 申请人",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ecs_cost_by_neworder_per1month) by (applicant)",
     "legendFormat": "{{applicant}}"
    }
   ]
  },
  { "title": "明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "明细",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "ecs_instance_cpu_usage_2130pm{applicant=~\"$applicant\", appType=~\"$appType\", dev=~\"$dev\"}"
    },
    {
     "expr": "sum(ecs_instance_mem_usage_lastday_p95{applicant=~\"$applicant\", appType=~\"$appType\", dev=~\"$dev\"})  by (instanceId)"
    },
    {
     "expr": "sum(ecs_cost_by_neworder_per1month{env=~\"env\", regionId=~\"$regionId\", status=~\"$status\",businessLine=~\"$businessLine\", project=~\"$project\", serverType=~\"$serverType\", serverName=~\"$serverName\", owner=~\"$owner\", applicant=~\"$applicant\"})  by (instanceId)"
    }
   ]
  }
 ]
}