apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-pushgateway-aliyun
  namespace: monitoring
  labels:
    app: prometheus-pushgateway-aliyun
data:
  prometheus.yml: >
    global:
      scrape_interval:     60s
      evaluation_interval: 60s

    scrape_configs:

      - job_name: 'pushgateway-aliyun-monitor'
        kubernetes_sd_configs:
        - role: pod
  
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_pushgateway, __meta_kubernetes_namespace]
          action: keep
          regex: pushgateway-aliyun;monitoring
